spring:
  mvc:
    view:
      suffix: jsp
      prefix: jsp
  datasource:
    url:
      jdbc:
        h2:
          mem: testdb
    driverClassName: org.h2.Driver
    username: sa
    password: null
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
server:
  port: 8081